changed endpoint for getting al hightlights. Status code is now 200 w…
DigitalExcellence/dex-backend pull request #248
Opened 2020-09-28 09:13 UTC by niraymak

…hen the list is emtpy.

## Description

A few sentences describing the overall goals of the pull request's commits.

## Type of change

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

## Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I did not update API Controllers, if I did, I added/changed Postman tests
-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes
-   [x] I updated the changelog with an end-user readable description
-   [x] I assigned this pull request to the correct project board to update the sprint board

## Steps to Test or Reproduce

1. Make sure there are no highlights in the database
2. Do a GET request to /api/Highlights (with right credentials)
3. Check if you receive an empty array with status code 200.

## Link to issue

Closes: #207

2020-09-28 12:21 UTC, Brend-Smits commented
Hey @niraymak are there other endpoints from other controllers that will also need changing? I wonder if this is the only endpoint with this issue.

2020-09-28 12:32 UTC, niraymak commented
> Hey @niraymak are there other endpoints from other controllers that will also need changing? I wonder if this is the only endpoint with this issue.

Following endpoint should be changed:

- GetAllEmbeddedProjects also sends 404.
- GetAllRoles sends 404 if list.count == 0.
- GetAllPossibleScopes sends 404 if list.count == 0.

Shall I change them and push them to this PR?

2020-09-28 12:54 UTC, niraymak commented
> > Hey @niraymak are there other endpoints from other controllers that will also need changing? I wonder if this is the only endpoint with this issue.
> 
> Following endpoint should be changed:
> 
> * GetAllEmbeddedProjects also sends 404.
> * GetAllRoles sends 404 if list.count == 0.
> * GetAllPossibleScopes sends 404 if list.count == 0.
> 
> Shall I change them and push them to this PR?

Changed the endpoints and pushed them to the PR

2020-09-28 12:58 UTC, Brend-Smits commented
Awesome, thanks @niraymak. Please also change the postman tests ^^'

2020-09-29 07:22 UTC, niraymak commented
@Brend-Smits test results are 100%. The corresponding tests already check for status code 200. I am not sure what to update in the Postman tests. Can you tell me what tests I should add?

2020-09-29 12:51 UTC, Brend-Smits commented
> @Brend-Smits test results are 100%. The corresponding tests already check for status code 200. I am not sure what to update in the Postman tests. Can you tell me what tests I should add?

Ah right, we don't have any tests for checking status codes when there are no entries. That's fine.

2020-10-06 13:06 UTC, Brend-Smits requested changes
Remove try-catch as discussed in Teams and we're good to go.

2020-10-06 16:03 UTC, Brend-Smits requested changes

2020-10-06 16:03 UTC, Brend-Smits commented on API/Controllers/RoleController.cs
> +            List<string> scopeList;
I think this section should be reverted to the way it was before.

2020-10-07 09:41 UTC, Brend-Smits commented
Since #240 is now merged, make sure the documentation is updated!

2020-10-08 13:13 UTC, Brend-Smits approved these changes

2020-10-09 09:46 UTC, merged