Feature/229 ability to like projects
DigitalExcellence/dex-backend pull request #251
Opened 2020-09-30 17:16 UTC by aintabb

## Description

- Added a new endpoint to the API for ability to like a project
- Fixed some of the typo issues
- Trimmed additional spaces.

## Type of change

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [x] This change requires a documentation update

## Checklist

-   [x] My code follows the style guidelines of this project
-   [ ] I did not update API Controllers, if I did, I added/changed Postman tests
-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes
-   [ ] I updated the changelog with an end-user readable description
-   [ ] I assigned this pull request to the correct project board to update the sprint board

## Steps to Test or Reproduce

1. Start Postman
2. Create a new request.
3. Select the request type PUT
4. Use "/project/{{projectId}}/like/{{userId}}" as a request template.
5. Run the test
6. You should see the userIds who liked the project in project table.

## Link to issue

Closes: [#229](https://github.com/DigitalExcellence/dex-backend/issues/229)

2020-09-30 17:20 UTC, aintabb commented
@Brend-Smits Please review this pull request and give me some feedback. So that i could continue to progress.

2020-10-02 12:01 UTC, niraymak requested changes
Thanks for your first pull request :)

I think you should look into implementing a ManyToMany relationship for project likes.
https://www.learnentityframeworkcore.com/configuration/many-to-many-relationship-configuration

I think there should be a new table called ProjectLike which has references FK_userId, FK_projectId.
All records in this table represent "likes".

After you've done the above, you will be able to get all likes from the project entity.

You can also look into @MeesvanStraten 's and @DaveBouman which is very similar. Their changes are on the branch underneath.
https://github.com/DigitalExcellence/dex-backend/tree/feature/228-follow-users-projects

2020-10-02 18:19 UTC, aintabb commented on API/Controllers/ProjectController.cs
> +        public async Task<IActionResult> LikeProject(int projectId, int userId)
Thanks a lot for your review @niraymak. I'll review your recommendations and make the necessary corrections.
I appreciate your time and effort for reviewing my pull request.

2020-10-06 05:54 UTC, aintabb commented on API/Controllers/ProjectController.cs
> +        public async Task<IActionResult> LikeProject(int projectId, int userId)
I believe I did all the necessary changes. 
I followed @MeesvanStraten 's and @DaveBouman's commits for ability to follow projects and users.

2020-10-07 09:42 UTC, Brend-Smits commented
Since #240 is now merged, make sure the documentation is updated!

2020-10-07 18:28 UTC, aintabb commented
@Brend-Smits Ok, I will take a look.

2020-11-09 08:47 UTC, Brend-Smits commented
@MeesvanStraten since your branch is now merged. It can be used as a blueprint. Could you take lead on reviewing this pull request and provide feedback for @aintabb to process, please?

2020-11-19 17:25 UTC, aintabb commented
@niraymak The long wait is finally over. Thanks for the review. @Brend-Smits I could be more useful, if you can speed up the review process.

2020-11-20 10:39 UTC, niraymak commented
@aintabb No worries! I created an internal branch called feature/229-ability-to-like-projects on our side. I added new Postman tests and renamed the table / models. Can you merge our branch into your branch? I think it should be ready to review then.

2020-11-21 20:02 UTC, aintabb commented
@niraymak Sure, I can do that.

2020-11-21 22:43 UTC, aintabb commented
@niraymak OK, I merged the changes from your branch to your branch. It seems you only changed the naming throughout the project. May I ask the reason? When I was designing the new feature, I thought "LikedProjectByUser"  would be more concise and descriptive

2020-11-23 12:10 UTC, niraymak commented
> @niraymak OK, I merged the changes from your branch to your branch. It seems you only changed the naming throughout the project. May I ask the reason? When I was designing the new feature, I thought "LikedProjectByUser" would be more concise and descriptive

Thanks for merging! I thought ProjectLike was shorter and describes the same thing. To be honest I think it is obvious a project is liked by a user. Any second opinions on this? @Brend-Smits @waltersajtos 

Thanks for your great code! 😁

2020-11-23 12:16 UTC, waltersajtos commented
For now, it is obvious that a project is liked by a user. I can't think of any case that you could like something else on the platform. Although I think that being concise and descriptive is more important than having the shortest name possible. I think it's just a case of personal preference since - as Niray said - it describes the same thing.

2020-11-23 12:25 UTC, waltersajtos submitted a review, later dismissed

2020-11-24 05:34 UTC, aintabb commented
> For now, it is obvious that a project is liked by a user. I can't think of any case that you could like something else on the platform. Although I think that being concise and descriptive is more important than having the shortest name possible. I think it's just a case of personal preference since - as Niray said - it describes the same thing.

Got it! Thanks for the comments @niraymak @waltersajtos I just wanted hear your thinking. That’s all.

2020-11-25 13:49 UTC, niraymak reviewed
Only had some issues starting without a database. It crashed the first time, second time it worked. I'm asking the team in Slack if this will cause any issues when merging to develop. 

No other comments. 💯

2020-11-30 09:38 UTC, MeesvanStraten approved these changes

2020-11-30 16:53 UTC, aintabb commented on API/Resources/UserProjectLikeResource.cs
> +        public User CreatorOfProject { get; set; }
Hi @MeesvanStraten , 
To my way of thinking, the summary explains clearly that "CreatorOfProject" points out the owner of the project.
Let's check the summary together; "Gets or sets the user who **_created the project_**". I think it is clear?

2020-12-02 10:32 UTC, niraymak approved these changes
🥇

2020-12-02 10:33 UTC, MeesvanStraten submitted a review, later dismissed

2020-12-02 10:35 UTC, MeesvanStraten approved these changes

2020-12-02 10:40 UTC, niraymak approved these changes

2020-12-02 13:37 UTC, merged