Added functionality to remove the projectIcon from the database and f…
DigitalExcellence/dex-backend pull request #294
Opened 2020-11-04 10:14 UTC by waltersajtos

…ilesystem when a project is updated/ deleted

## Description

A few sentences describing the overall goals of the pull request's commits.

## Type of change

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

## Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I did not update API Controllers, if I did, I added/changed Postman tests
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes
-   [ ] I updated the changelog with an end-user readable description
-   [ ] I assigned this pull request to the correct project board to update the sprint board

## Steps to Test or Reproduce

Outline the steps to test or reproduce the PR here.
These steps will be used during release testing.

1. Do something here...
2. Then run this test...
3. After that, you should see the result here

## Link to issue

Closes: #issuenumber

2020-11-18 09:34 UTC, Brend-Smits requested changes

2020-11-18 09:34 UTC, Brend-Smits commented on API/Controllers/ProjectController.cs
> +                                 IFileUploader fileUploader,
"Parameter 'fileUploader' has no matching param tag in the XML comment for 'ProjectController.ProjectController(IProjectService, IUserService, IMapper, IAuthorizationHelper, IFileService, IFileUploader, IUserProjectService)' (but other parameters do)
"

2020-11-18 09:34 UTC, Brend-Smits commented on API/Controllers/ProjectController.cs
> +            /*// Check if the icon has been changed
Commented out code?

2020-11-18 09:34 UTC, Brend-Smits commented on API/Controllers/ProjectController.cs
> +                    Instance = "2E765D18-8EBC-4117-8F9E-B800E8967038"
GUID is not unique, generate a fresh one using Visual Studio or an online tool please.

2020-11-18 09:34 UTC, Brend-Smits commented on API/Controllers/ProjectController.cs
> +                        Instance = "69166D3D-6D34-4050-BD25-71F1BEBE43D3"
GUID is not unique, generate a fresh one using Visual Studio or an online tool, please.

2020-11-18 11:59 UTC, niraymak requested changes
Tests work! Except for Brend's request no more requests for me. 👍

2020-11-19 10:23 UTC, Brend-Smits approved these changes
Awesome! Thank you :)

2020-11-19 11:00 UTC, niraymak approved these changes
Good work 👍

2020-11-19 11:01 UTC, Brend-Smits approved these changes

2020-11-19 11:02 UTC, niraymak approved these changes

2020-11-19 11:10 UTC, merged