Feature/317 include collaborators project overview
DigitalExcellence/dex-backend pull request #318
Opened 2020-11-29 18:12 UTC by waltersajtos

## Description

A few sentences describing the overall goals of the pull request's commits.

## Type of change

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

## Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I did not update API Controllers, if I did, I added/changed Postman tests
-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes
-   [x] I updated the changelog with an end-user readable description
-   [x] I assigned this pull request to the correct project board to update the sprint board

## Steps to Test or Reproduce

Outline the steps to test or reproduce the PR here.
These steps will be used during release testing.

1. Make a GET request to /api/project
2. The response should include the collaborators

## Link to issue
#317 

Closes: #317

2020-11-29 18:45 UTC, Ruby77 requested changes
I noticed you didn't add a description for this pull request. I understand it's a lot of work to add a description for a small issue like this. However, I don't think we need to skip them, I think it's important to create a description for small issues as well 😄 . 

And another small thing: do you think this is a New feature? Don't you think it's rather a bugfix (which fixes in issue for the frontend?).

Overall the good looks good and works like a charm

2020-11-29 18:45 UTC, Ruby77 commented on API/Resources/ProjectResultResource.cs
> +        public ICollection<CollaboratorResourceResult> Collaborators { get; set; }
Is there a reason why you would use ICollection over IEnumerable? I could be overlooking a thing of course. 

However, you could say the following:
- Use IEnumerable: for a list of objects that only needs to be iterated through
- Use ICollection: for a list of objects that needs to be iterated through and modified

And I don't think we need to modify them right?

2020-11-29 19:14 UTC, waltersajtos commented
> I noticed you didn't add a description for this pull request. I understand it's a lot of work to add a description for a small issue like this. However, I don't think we need to skip them, I think it's important to create a description for small issues as well 😄 .
> 
> And another small thing: do you think this is a New feature? Don't you think it's rather a bugfix (which fixes in issue for the frontend?).
> 
> Overall the good looks good and works like a charm

You are right, I edited the description but forgot to save it :)
I wasn't sure what to call it, since it isn't really a bug because the behavior was expected.

2020-11-30 08:12 UTC, Ruby77 approved these changes

2020-11-30 10:46 UTC, Brend-Smits approved these changes

2020-11-30 10:49 UTC, merged