Feature/256 notification system
DigitalExcellence/dex-backend pull request #322
Opened 2020-11-30 12:13 UTC by matir8

## Description
- Added initial version of the notification system using RabbitMQ as a message broker. 
- Unit and integration tests are going to be added in a separate issue

## Type of change

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [x] This change requires a documentation update

## Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I did not update API Controllers, if I did, I added/changed Postman tests
-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes
-   [x] I updated the changelog with an end-user readable description
-   [x] I assigned this pull request to the correct project board to update the sprint board

## Steps to Test or Reproduce

In order to use the notification system in the API use the following snippet:
```
NotificationSender sender = new NotificationSender();
EmailNotification notification = new EmailNotification("test@example.com", "plain text content");
sender.RegisterNotification(Newtonsoft.Json.JsonConvert.SerializeObject(notification), Subject.EMAIL);
```

## Link to issue

Closes: #256

2020-11-30 14:22 UTC, waltersajtos commented on NotificationSystem/Services/EmailSender.cs
> +            if (ValidateNotification(emailNotification))
Might be an idea to throw an expectation when the notification is invalid

2020-12-01 10:02 UTC, MeesvanStraten submitted a review, later dismissed
Got my email 🥇 , Code is solid and was able to get the email sent :)

2020-12-01 11:09 UTC, niraymak reviewed
Created an SendGrid account and added API key and was able to send plain HTML email! 👍 

I think we still need a general DeX SendGrid account. I was also wondering if the current implementation is able to send templates instead of plain HTML? I think this is a must for the near future but maybe for now plain HTML is OK. I will wait for Brend's feedback before approving.

2020-12-01 11:15 UTC, Brend-Smits requested changes
Appsettings should be used if possible, I will discuss this with you all in person

2020-12-01 13:38 UTC, Maxvanhattum commented
Use these variables in the .env file for testing purposes, change sendgrid credentials if you want to send emails:

```
App__RabbitMQ__Hostname=rabbitmq #if you run it from docker-compose use rabbitmq otherwise localhost for development environment
App__RabbitMQ__Username=test
App__RabbitMQ__Password=test
App__SendGrid__ApiKey=test
App__SendGrid__EmailFrom=test@gmail.com
```

2020-12-01 15:15 UTC, Brend-Smits commented
I've set up the SendGrid account and configured API keys for:
- Production
- Staging 
- Local development
All of these keys are stored in 1Password, everyone should have access to the Local Development key in there so they can test the email implementation when they want to. 

I'm gonna make some small changes to this code(https://github.com/DigitalExcellence/dex-backend/pull/322/files#diff-263557b791777f5b3ab458f4e289cd33f765c25fe77b1be8748397f09798e496R29-R46) later tonight and get the infrastructure ready and setup. 
I will keep you all posted!

2020-12-02 08:29 UTC, MeesvanStraten approved these changes

2020-12-02 11:50 UTC, Brend-Smits approved these changes

2020-12-02 11:56 UTC, niraymak approved these changes

2020-12-02 11:58 UTC, merged