Feature/313 get user projects
DigitalExcellence/dex-backend pull request #334
Opened 2020-12-04 11:49 UTC by waltersajtos

## Description

There is no way to retrieve a user's projects

## Type of change

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

## Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I did not update API Controllers, if I did, I added/changed Postman tests
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes
-   [ ] I updated the changelog with an end-user readable description
-   [ ] I assigned this pull request to the correct project board to update the sprint board

## Steps to Test or Reproduce

Outline the steps to test or reproduce the PR here.
These steps will be used during release testing.

1. Create a project on a user
2. Make a request to {dexAPI}/user/projects
3. The API should return the user's projects

## Link to issue
#313 

Closes: #313

2020-12-05 14:31 UTC, Brend-Smits requested changes

2020-12-05 14:31 UTC, Brend-Smits commented on API/Controllers/UserController.cs
> +            [HttpPost]
Formatting is off?

2020-12-05 14:31 UTC, Brend-Smits commented on API/Controllers/UserController.cs
> +            User user = await userService.GetUserByIdentityIdAsync(identityId);
I think you can just use the helper method GetContextUser

2020-12-05 14:31 UTC, Brend-Smits commented on Repositories/ProjectRepository.cs
> +                   .Include(p => p.Collaborators)
Refer to my PR #335 please

2020-12-05 14:31 UTC, Brend-Smits commented on Repositories/ProjectRepository.cs
> +        public async Task<IEnumerable<Project>> FindUserProjectsWithUserAndCollaboratorsAsync(int userId)
FindUserProjectsAsync is sufficient I think

2020-12-05 14:31 UTC, Brend-Smits commented on Services/Services/ProjectService.cs
> +            return Repository.FindUserProjectsWithUserAndCollaboratorsAsync(userId);
FindUserProjectsAsync is sufficient

2020-12-10 09:05 UTC, niraymak requested changes

2020-12-10 09:05 UTC, niraymak commented on API/Controllers/UserController.cs
> +        /// <param name="projectService">The project service which is responsible for retreiving the users projects</param>
Typo: retreiving -> retrieving

2021-01-18 10:32 UTC, waltersajtos commented
I still need to fix the merge conflicts for the tests, I will do this once #77 and #354 are merged so we don't need to fix the merge conflicts there

2021-02-25 19:16 UTC, niraymak requested changes
Great work! 

I found some redundant code which slows down our application. You can remove those the lines. I already tested it and it works.

2021-02-25 19:16 UTC, niraymak commented on Repositories/ProjectRepository.cs
> +            }
Collaborators are already included on line 298, right? I think these lines can be removed.

2021-02-25 19:19 UTC, niraymak commented on Repositories/ProjectRepository.cs
> +            }
> Great work!
> 
> I found some redundant code which slows down our application. You can remove those the lines. I already tested it and it works.

And don't forget to change the changelog

2021-02-25 19:21 UTC, Ruby77 requested changes
Looks good! I'll approve after you resolved Niray's feedback :smile:

2021-02-25 19:21 UTC, Ruby77 commented on Postman/dex.postman_collection.json
> +									"name": "Project-DeleteProject-Other-Registered Copy",
Replace copy by an actual name

2021-02-28 15:16 UTC, Ruby77 commented on CHANGELOG.md
> +- Added functionality to retrieve a users project - [#313](https://github.com/DigitalExcellence/dex-backend/issues/313)
Final request change :smile: . I will approve after this change!

```suggestion
- Added functionality to retrieve a user's project - [#313](https://github.com/DigitalExcellence/dex-backend/issues/313)
```

2021-03-01 08:21 UTC, Ruby77 requested changes

2021-03-01 08:21 UTC, Ruby77 commented on CHANGELOG.md
> +- Added ability to retreive all user projects - [#313](https://github.com/DigitalExcellence/dex-backend/issues/313)
```suggestion
- Added ability to retrieve all the user's projects - [#313](https://github.com/DigitalExcellence/dex-backend/issues/313)
```

2021-03-01 08:22 UTC, Ruby77 approved these changes
Good work. Everything works as expected!

2021-03-02 14:13 UTC, niraymak approved these changes
💯

2021-03-03 08:27 UTC, merged