Update recourses and models
DigitalExcellence/dex-backend pull request #449
Opened 2021-05-31 08:15 UTC by waltersajtos

## Description

Implement the categories in the projectFilter, I also made some changes to the resources and authorization for the category routes so everything is consistent.

## Type of change

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

## Checklist

-   [x] My code follows the style guidelines of this project
-   [ ] I did not update API Controllers, if I did, I added/changed Postman tests
-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes
-   [ ] I updated the changelog with an end-user readable description
-   [ ] I assigned this pull request to the correct project board to update the sprint board

## Steps to Test or Reproduce

Outline the steps to test or reproduce the PR here.
These steps will be used during release testing.

1. Add a project with a category
2. GetAll projects and add the category you added to the project
3. You should only get the project you created

## Link to issue

Closes: #444

2021-06-02 11:43 UTC, niraymak requested changes
Only Postman tests left?

2021-06-02 11:43 UTC, niraymak commented on API/Resources/ProjectFilterParamsResource.cs
> +        ///     Get or Set the direction of sorting by query parameter.F
```suggestion
        ///     Get or Set the direction of sorting by query parameter.
```

2021-06-02 14:20 UTC, niraymak approved these changes

2021-06-03 10:15 UTC, niraymak submitted a review, later dismissed

2021-06-04 07:21 UTC, RubenFricke approved these changes

2021-06-04 07:41 UTC, RubenFricke approved these changes

2021-06-04 08:02 UTC, niraymak approved these changes

2021-06-04 08:03 UTC, RubenFricke approved these changes

2021-06-04 08:12 UTC, merged