Feature/379 automated performance tests
DigitalExcellence/dex-backend pull request #460
Opened 2021-06-15 09:09 UTC by BluRRayS

## Description

Executing performance tests against staging or production with K6.
I, Ramon And Tim have written some tests to test the performance of the getProjects endpoint since it is a hot endpoint and often used. We wrote Load, Soak and stress tests and we wrote documentation on how to write and execute tests in the Wiki.

The documentation can be found [here](https://github.com/DigitalExcellence/dex-backend/wiki/Perfomancing-testing).
And the research [here]().

## Type of change

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [X] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

## Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I did not update API Controllers, if I did, I added/changed Postman tests
-   [X] I have performed a self-review of my own code
-   [X] I have commented my code, particularly in hard-to-understand areas
-   [X] I have made corresponding changes to the documentation
-   [X] I have added tests that prove my fix is effective or that my feature works
-   [X] New and existing unit tests pass locally with my changes
-   [X] I updated the changelog with an end-user readable description
-   [X] I assigned this pull request to the correct project board to update the sprint board

## Steps to Test or Reproduce

You can run the performance tests using any CLI on a system that has docker and docker-compose installed.
Run tests by navigating to the `PerformanceTests` folder and then executing the commands state in the documentation found [here](https://github.com/DigitalExcellence/dex-backend/wiki/Perfomancing-testing)

[#379 ](https://github.com/DigitalExcellence/dex-backend/issues/379)

Closes #379 Performance tests

2021-06-18 09:15 UTC, niraymak approved these changes
Great job guys! Good start for performance testing! 🥇

2021-06-22 10:22 UTC, niraymak requested changes

2021-06-22 10:22 UTC, niraymak commented on API/appsettingsapi.Development.json
> +            "Password": "guest"
```suggestion
            "Username": "test",
            "Password": "test"
```

2021-06-22 10:25 UTC, Maxvanhattum approved these changes
Seems to be a good basis

2021-06-22 10:25 UTC, Maxvanhattum commented on API/appsettingsapi.Development.json
> +            "Password": "guest"
If using docker leave it on test test

2021-06-22 10:26 UTC, niraymak approved these changes

2021-06-22 10:26 UTC, Maxvanhattum approved these changes

2021-06-22 11:42 UTC, merged