Feature/377 fontys gitlab datasource to wizard
DigitalExcellence/dex-backend pull request #462
Opened 2021-06-17 12:02 UTC by TimSnoek123

## Description

Added the functionality to search for repositories using the Fontys Gitlab, private projects for gitlab should also work. @rubenb994 can you maybe test if gitlab still works? I don't have the client secret etc...

## Type of change

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [X] New feature (non-breaking change which adds functionality)
-   [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

## Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I did not update API Controllers, if I did, I added/changed Postman tests
-   [X] I have performed a self-review of my own code
-   [X] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [X] New and existing unit tests pass locally with my changes
-   [X] I updated the changelog with an end-user readable description
-   [X] I assigned this pull request to the correct project board to update the sprint board

## Steps to Test or Reproduce

1. Get a user token, clientid and clientsecret from the Fontys Gitlab (in your user settings).
2. Open swagger and check all 3 wizard endpoints using the token and other meta data specific to the request.
3. Check if gitlab works with private and public projects.

## Link to issue

Closes: #377

2021-06-18 08:48 UTC, TimSnoek123 commented
Currently the integration tests are executing really slowly compared to develop. This also causes them to fail, don't know why this happens. :(

2021-06-18 13:50 UTC, niraymak commented
Worked like a charm. I would like to check the GitHub private flow again. Didn't get it working. Will check next week together with @RubenFricke

2021-06-18 13:52 UTC, TimSnoek123 commented
Don't know if the github private flow works yet tbh we mostly focused on gitlab.

2021-06-22 08:16 UTC, niraymak requested changes
Thanks for your implementation 💯 

Can you please change RabbitMQ appsettings back to docker credentials. 
Also please remove GitLab API key.

2021-06-22 08:16 UTC, niraymak commented on API/appsettingsapi.Development.json
> +            "Username": "guest",
please change back to "test", "test"

2021-06-22 08:16 UTC, niraymak commented on API/appsettingsapi.Development.json
> +                "OauthUrl": "https://git.fhict.nl/oauth/authorize?client_id={0}&redirect_uri={1}&response_type=code&scope=read_repository+read_user"
I think this should be removed, right? Or can it be used for development?

@RubenFricke we should add FHICT GitLab API keys to staging / production

2021-06-23 11:11 UTC, niraymak requested changes

2021-06-23 11:11 UTC, niraymak commented on API/appsettingsapi.Development.json
> +                "RedirectUri": "https://localhost:5001/api/wizard/oauth/callback/66de59d4-5db0-4bf8-a9a5-06abe8d3443a",
```suggestion
                "RedirectUri": "",
```

2021-06-23 11:11 UTC, niraymak commented on API/appsettingsapi.Development.json
> +                "OauthUrl": "https://gitlab.com/oauth/authorize?client_id={0}&redirect_uri={1}&response_type=code&scope=read_repository+read_user"
```suggestion
                "OauthUrl": ""
```

2021-06-23 11:11 UTC, niraymak commented on API/appsettingsapi.Development.json
> +                "ClientId": "536f6b353a9ecea950f69e9141ce87579376c279d7201c42099266a768148632",
```suggestion
                "ClientId": "",
```

2021-06-23 11:11 UTC, niraymak commented on API/appsettingsapi.Development.json
> +                "ClientSecret": "627a2ce856d47c95878e1dce2ada57ec135d3021fe916b1590f4cee6ddae37d7",
```suggestion
                "ClientSecret": "",
```

2021-06-23 11:11 UTC, niraymak commented on API/appsettingsapi.Development.json
> +                "RedirectUri": "https://localhost:5001/api/wizard/oauth/callback/6a73f5ee-e7a5-4ef5-b874-0da0993d6f13",
```suggestion
                "RedirectUri": "",
```

2021-06-23 11:11 UTC, niraymak commented on API/appsettingsapi.Development.json
> +            "Username": "guest",
```suggestion
            "Username": "test",
```

2021-06-23 11:11 UTC, niraymak commented on API/appsettingsapi.Development.json
> +            "Password": "guest"
```suggestion
            "Password": "test"
```

2021-06-23 11:17 UTC, niraymak approved these changes

2021-06-28 11:46 UTC, RubenFricke approved these changes
Good work guys!

2021-06-28 11:46 UTC, merged