Feature/461 add pagination getuserprojects endpoint
DigitalExcellence/dex-backend pull request #504
Opened 2021-09-21 08:15 UTC by BartvanEijkelenburg

## Description

A few sentences describing the overall goals of the pull request's commits.

## Type of change

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

## Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I did not update API Controllers, if I did, I added/changed Postman tests
-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [x] I have added tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes
-   [ ] I updated the changelog with an end-user readable description
-   [x] I assigned this pull request to the correct project board to update the sprint board

## Steps to Test or Reproduce

Run the project.

Go to swagger or Postman, log in as bob bob.

Select the Get User projects endpoint and try it out with the pagination options.

## Link to issue
Closes: #461

2021-09-30 10:49 UTC, MeesvanStraten commented on Postman/dex.postman_collection.json
> +										"url": null
As we spoke about on Teams, all looks good except this url probably caused the tests to fail.

2021-09-30 10:50 UTC, MeesvanStraten commented on Postman/dex.postman_collection.json
> +										"url": null
same as above ^^

2021-09-30 10:50 UTC, MeesvanStraten requested changes
see comments for postman tests.

2021-10-04 07:58 UTC, MeesvanStraten approved these changes

2021-10-04 08:06 UTC, BasvanMil approved these changes

2021-10-04 08:06 UTC, DaveBouman approved these changes
Look good

2021-10-04 08:08 UTC, merged